FinalProject_1933112/Controllers/AppartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject_1933112.Models;

namespace FinalProject_1933112.Controllers
{
    public class AppartmentsController : Controller
    {
        private PropertyManagementDBEntities3 db = new PropertyManagementDBEntities3();

        // GET: Appartments
        public ActionResult Index()
        {
            var appartments = db.Appartments.Include(a => a.Manager).Include(a => a.Tenant);
            return View(appartments.ToList());
        }



        // GET: Appartments/Details/5
        public ActionResult Details()
        {
            var appartments = db.Appartments.Include(a => a.Manager).Include(a => a.Tenant);
            return View(appartments.ToList());

            

            
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Appartment appartment = db.Appartments.Find(id);
            //if (appartment == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(appartment);
            

        }

        // GET: Appartments/Create
        public ActionResult Create()
        {
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName");
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName");
            return View();
        }

        // POST: Appartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppartmentID,Status,TenantID,ManagerID")] Appartment appartment)
        {
            if (ModelState.IsValid)
            {
                db.Appartments.Add(appartment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", appartment.ManagerID);
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", appartment.TenantID);
            return View(appartment);
        }

        // GET: Appartments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartment appartment = db.Appartments.Find(id);
            if (appartment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", appartment.ManagerID);
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", appartment.TenantID);
            return View(appartment);
        }

        // POST: Appartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AppartmentID,Status,TenantID,ManagerID")] Appartment appartment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appartment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", appartment.ManagerID);
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", appartment.TenantID);
            return View(appartment);
        }

        // GET: Appartments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartment appartment = db.Appartments.Find(id);
            if (appartment == null)
            {
                return HttpNotFound();
            }
            return View(appartment);
        }

        // POST: Appartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appartment appartment = db.Appartments.Find(id);
            db.Appartments.Remove(appartment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject_1933112/Controllers/BuildingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject_1933112.Models;

namespace FinalProject_1933112.Controllers
{
    public class BuildingsController : Controller
    {
        private PropertyManagementDBEntities3 db = new PropertyManagementDBEntities3();

        // GET: Buildings
        public ActionResult Index()
        {
            var buildings = db.Buildings.Include(b => b.Appartment).Include(b => b.Manager);
            return View(buildings.ToList());
        }

        public ActionResult ListBuildings()
        {
            var buildings = db.Buildings.Include(m => m.Manager);
            return View(buildings.ToList());

        }

        // GET: Buildings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Building building = db.Buildings.Find(id);
            if (building == null)
            {
                return HttpNotFound();
            }
            return View(building);
        }

        // GET: Buildings/Create
        public ActionResult Create()
        {
            ViewBag.AppartmentID = new SelectList(db.Appartments, "AppartmentID", "AppartmentID");
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName");
            return View();
        }

        // POST: Buildings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BuildingID,nbAppartments,AppartmentID,ManagerID")] Building building)
        {
            if (ModelState.IsValid)
            {
                db.Buildings.Add(building);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AppartmentID = new SelectList(db.Appartments, "AppartmentID", "AppartmentID", building.AppartmentID);
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", building.ManagerID);
            return View(building);
        }

        // GET: Buildings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Building building = db.Buildings.Find(id);
            if (building == null)
            {
                return HttpNotFound();
            }
            ViewBag.AppartmentID = new SelectList(db.Appartments, "AppartmentID", "AppartmentID", building.AppartmentID);
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", building.ManagerID);
            return View(building);
        }

        // POST: Buildings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BuildingID,nbAppartments,AppartmentID,ManagerID")] Building building)
        {
            if (ModelState.IsValid)
            {
                db.Entry(building).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AppartmentID = new SelectList(db.Appartments, "AppartmentID", "AppartmentID", building.AppartmentID);
            ViewBag.ManagerID = new SelectList(db.Managers, "ManagerID", "FirstName", building.ManagerID);
            return View(building);
        }

        // GET: Buildings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Building building = db.Buildings.Find(id);
            if (building == null)
            {
                return HttpNotFound();
            }
            return View(building);
        }

        // POST: Buildings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Building building = db.Buildings.Find(id);
            db.Buildings.Remove(building);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject_1933112/Controllers/ManagersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FinalProject_1933112.Models;

namespace FinalProject_1933112.Controllers
{
    public class ManagersController : Controller
    {
        private PropertyManagementDBEntities3 db = new PropertyManagementDBEntities3();

        // GET: Managers
        //public ActionResult Index()
        //{
        //   var managers = db.Managers.Include(m => m.Tenant);
        //    //return View(managers.ToList());
        //    return View();
        //}

        
        public ActionResult Index(Manager model)
        {
            using (PropertyManagementDBEntities3 db = new PropertyManagementDBEntities3())
            {
                bool isValidUser = db.Managers.Any(user => user.FirstName.ToLower() ==
                model.FirstName.ToLower() && user.Password == model.Password);
                if (isValidUser)
                {
                    FormsAuthentication.SetAuthCookie(model.FirstName, false);
                    
                    var fname = model.FirstName;

                    var test = db.Managers.FirstOrDefault(p => p.FirstName == fname);
                    var test2 = test.ManagerID;

                    string x = "Details/" + test2.ToString();
                    return RedirectToAction(x, "Managers");
                }
                ModelState.AddModelError("", "Invalid username or password !");
                return View();
            }
        }

        public ActionResult ListManagers()
        {
            var managers = db.Managers.Include(m => m.Owners);
            return View(managers.ToList());
            
        }

        // GET: Managers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manager manager = db.Managers.Find(id);
            if (manager == null)
            {
                return HttpNotFound();
            }
            return View(manager);
        }

        // GET: Managers/Create
        public ActionResult Create()
        {
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName");
            return View();
        }

        // POST: Managers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ManagerID,FirstName,LastName,Password,TenantID")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                db.Managers.Add(manager);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", manager.TenantID);
            return View(manager);
        }

        // GET: Managers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manager manager = db.Managers.Find(id);
            if (manager == null)
            {
                return HttpNotFound();
            }
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", manager.TenantID);
            return View(manager);
        }

        // POST: Managers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ManagerID,FirstName,LastName,Password,TenantID")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TenantID = new SelectList(db.Tenants, "tenantID", "firstName", manager.TenantID);
            return View(manager);
        }

        // GET: Managers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manager manager = db.Managers.Find(id);
            if (manager == null)
            {
                return HttpNotFound();
            }
            return View(manager);
        }

        // POST: Managers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Manager manager = db.Managers.Find(id);
            db.Managers.Remove(manager);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject_1933112/Views/Managers/Create.cshtml
@model FinalProject_1933112.Models.Manager

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ManagerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenantID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenantID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalProject_1933112/Views/Managers/Delete.cshtml
@model FinalProject_1933112.Models.Manager

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tenant.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenant.firstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinalProject_1933112/Views/Managers/Details.cshtml
@model FinalProject_1933112.Models.Manager

@{
    ViewBag.Title = "Details";
}

<h2>Managers Options</h2>

<button onclick="location.href='@Url.Action("ListBuildings", "Buildings")';return false;">List all Buildings</button>
<button onclick="location.href='@Url.Action("Create", "Buildings")';return false;">Create new Building</button>

<br>


<input type="text" id="id2" name="id2">
<br>
<button onclick="location.href='@Url.Action("Edit", "Buildings")';return false;">Edit Building</button>
<button onclick="location.href='@Url.Action("Delete", "Buildings")';return false;">Delete Building</button>


<br>
<hr>


<h2>Tenants Options</h2>
<button onclick="location.href='@Url.Action("List", "Tenants")';return false;">List all Tenants</button>
<button onclick="location.href='@Url.Action("Create", "Tenants")';return false;">Create new Tenant</button>

<br>


<input type="text" id="id2" name="id2">
<br>
<button onclick="location.href='@Url.Action("Edit", "Tenants")';return false;">Edit Tenant</button>
<button onclick="location.href='@Url.Action("Delete", "Tenants")';return false;">Delete Tenant</button>
<br>
<hr />
<h3>Appartment Status</h3>
<button onclick="location.href='@Url.Action("Index", "Appartments")';return false;">List all Appartments</button>






@*<hr />
    <div>
        <h4>Manager Profile</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Manager.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Manager.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tenant.firstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tenant.firstName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ManagerID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@



@*@model FinalProject_1933112.Models.Manager

    @{
        ViewBag.Title = "Details";
    }

    <h2>Details</h2>

    <div>
        <h4>Manager</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tenant.firstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tenant.firstName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ManagerID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

FinalProject_1933112/Views/Managers/Edit.cshtml
@model FinalProject_1933112.Models.Manager

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ManagerID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenantID, "TenantID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TenantID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalProject_1933112/Views/Managers/Index.cshtml
@model FinalProject_1933112.Models.Manager

@{
    ViewBag.Title = "Managers Login Page";
}


@using (Html.BeginForm())
{
    <center>
        <div class="bs-example" style="border:2px solid gray;">

            <div class="form-group centerlook">
                <h1> Manager Login </h1>
            </div>
            <div class="form-group centerlook">
                <label>User Name: </label>
                @Html.EditorFor(model => model.FirstName)*
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
            <div class="form-group centerlook">
                <label>Password:</label>
                @Html.EditorFor(model => model.Password)*
                @Html.ValidationMessageFor(model => model.Password)

            </div>
            <div class="form-group error">
                @if (@ViewBag.Failedcount != null)
                {

                    <label> Failed Attempt count is: @ViewBag.Failedcount</label>
                }

                @if (@ViewBag.NotValidUser != null)
                {

                    <label> @ViewBag.NotValidUser</label>
                }
            </div>
            <div class="loginbtn">

                <input type="submit" value="Login" class="btn btn-primary" />

            </div>
            <button onclick="location.href='@Url.Action("Create", "Tenants")';return false;">Create an Account</button>
        </div>
        <button onclick="location.href='@Url.Action("LoginPage", "Home")';return false;">Back to main page</button>
    </center>
}

@*
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tenant.firstName)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tenant.firstName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ManagerID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ManagerID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ManagerID })
            </td>
        </tr>
    }

    </table>
*@

FinalProject_1933112/Views/Managers/ListManagers.cshtml
@model IEnumerable<FinalProject_1933112.Models.Manager>

@{
    ViewBag.Title = "ListManagers";
}

<h2>ListManagers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManagerID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManagerID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ManagerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ManagerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ManagerID })
        </td>
    </tr>
}

</table>
<button onclick="location.href='@Url.Action("", "Managers")';return false;">Back to Owner's Page</button>